[package]
name = "baryuxn"
version = "0.1.0"
edition = "2021"
authors = ["Alo√Øs Rautureau <alois.rautureau@ens-rennes.fr>"]
license = "Unlicense"
description = "An implementation of the Uxn stack machine designed to not rely on the standard library."
